name: Medigo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cloud_firestore: ^0.13.4+2
  cupertino_icons: ^0.1.2
  email_validator: ^1.0.0
  firebase_auth: ^0.15.5+3 
  firebase_storage: ^3.1.3
  fluttertoast: ^4.0.1
  flutter_svg: ^0.17.4
  geolocator: ^5.3.1
  google_nav_bar: ^2.2.0
  google_sign_in: ^4.5.1
  image_picker: ^0.6.3+4
  line_icons: ^0.2.0
  path: ^1.6.4
  permission_handler: ^4.4.0+hotfix.2
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Varela
      fonts:
        - asset: assets/fonts/Varela-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
